### ISSUE TITLE
Error on JSON validation for custom attribute

### ISSUE THREAD

**Issue by asifma** [aws-solutions/cloud-migration-factory-on-aws#33] opened 2024-02-15 15:56 UTC
**Describe the bug**
When attempting to edit a server in the front-end, an error occurs with the message "**Invalid JSON: "[object Object]**" is not valid JSON." The issue seems to be related to the initial validation of the JSON attribute when loading the edit page for the server object.
The UI gives the indication that something is wrong with the json, but it's not and it further impacts the possibility to save any changes before the validation error is gone. 

**To Reproduce**

1. Create a custom JSON attribute.
2. Populate the custom JSON attribute within a CMF Automation job.
3. Navigate to the front-end and attempt to edit the server with the custom JSON attribute.
4. Encounter the error: "Invalid JSON: "[object Object]" is not valid JSON."

**Expected behavior**
Editing the server with the custom JSON attribute should not result in a JSON validation error. The JSON object has the correct format, and the validation should not raise an error when loading the edit page.

**Please complete the following information about the solution:**
- [ ] Version: **V3.3.0**

- [ ] Region: **us-east-1**
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? **N/A**
- [ ] Were there any errors in the CloudWatch Logs? **NO**

**Screenshots**
![Screenshot 2024-02-15 at 4 27 21 PM](https://github.com/aws-solutions/cloud-migration-factory-on-aws/assets/27285709/a0959b60-9b9f-428b-8614-a7b8b654e640)

**Additional context**
Upon further investigation, I believe the issue is related to the initial validation when loading the edit page for the server object. The problem seems to be occurring in the file [JsonAttribute.tsx](https://github.com/aws-solutions/cloud-migration-factory-on-aws/blob/main/source/frontend/src/components/ui_attributes/JsonAttribute.tsx). The validation error disappears when any character is added to a property, indicating that the JSON object is correctly formatted, and the issue might be in the validation process during the initial page load.

**Comment by abe-aws** [comment] 2024-02-15 21:19
Thanks for the filing the bug.
I couldn't reproduce it with a simple JSON. We will look into it.

**Comment by asifma** [comment] 2024-02-16 00:43
Hi, would be happy to give you more insights on slack. Just ping me.

**Comment by abe-aws** [comment] 2024-02-21 15:06
Fix will be included in the next release.

**Comment by chris-p-baker** [comment] 2024-04-16 15:42
We have now implemented this fix in v3.3.4.

**Closed by chris-p-baker** 2024-04-16 15:42 UTC
Labels: bug, triaged
